name: spotify_creator_growth
version: '1.0.0'
config-version: 2

profile: spotify_creator_growth

model-paths: ["models"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  spotify_creator_growth:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
